#include <string>
#include <vector>

void generateTree(std::string const &name, std::string const &dir = ".") {
   TFile f((dir + "/" + name + ".root").c_str(), "RECREATE"); // Create file
   TTree tree(name.c_str(), "Tree with basic leaf variables"); // Create tree

   // Leaf variables
   Float_t px, py, pz;
   Double_t random;
   Int_t ev;

   // Each variable has a separate branch
   tree.Branch("px",&px,"px/F");
   tree.Branch("py",&py,"py/F");
   tree.Branch("pz",&pz,"pz/F");
   tree.Branch("random",&random,"random/D");
   tree.Branch("ev",&ev,"ev/I");

   // Fill tree
   for (Int_t i = 0; i < 10; ++i) {
      px     = 100 + i;
      py     = 200 + i;
      pz     = 300 + i;
      random = 400 + i;
      ev     = 500 + i;
      tree.Fill();
   }

   f.Write(); f.Close(); // Write tree to file
}

// Simple structure to hold the data
struct simple_t {
   Float_t px, py, pz;
   Int_t ev;
};

simple_t simple; // An instance of the structure to generate the data

void generateTreeStruct(std::string const &name, std::string const &dir = ".") {
   TFile f((dir + "/" + name + ".root").c_str(), "RECREATE"); // Create file
   TTree tree(name.c_str(), "Tree from a C structure with basic variables"); // Create tree

   // A single branch contains all variables
   tree.Branch("simple", &simple, "px/F:py/F:pz/F:ev/I");

   // Fill tree
   for (Int_t i = 0; i < 10; ++i) {
      simple.px = 100 + i;
      simple.py = 200 + i;
      simple.pz = 300 + i;
      simple.ev = 500 + i;
      tree.Fill();
   }

   f.Write(); f.Close(); // Write tree to file
}

// Generate trees
void generateAll() {
   std::string const dir = "./trees";
   generateTree("Tree", dir);
   generateTreeStruct("TreeStruct", dir);
}

// Run all tests (assuming that the trees are already generated by
// 'generateAll()' and the selectors are implemented in files
// 'selector.C_filled')
void testSimple() {
   const char *dirSaved = gSystem->pwd(); // Save working directory
   gSystem->cd("./trees"); // Go to trees

   // Loop through test trees
   std::vector<std::string> trees = {"Tree", "TreeStruct"};
   for (std::string treeName : trees)
   {
      fprintf(stderr, "Testing tree %s\n", treeName.c_str());
      TFile f((treeName + ".root").c_str());        // Load file
      TTree *t = (TTree*)f.Get(treeName.c_str());   // Load tree
      t->MakeSelector();                            // Generate selector
      t->Process((treeName + "_filled.C").c_str()); // Run (pre-filled) selector
   }
   gSystem->cd(dirSaved); // Restore working directory
}
