R__LOAD_LIBRARY(SampleClasses_h.so)
#include "SampleClasses.h"
#include <string>
#include <vector>
#include "TClonesArray.h"

void generateTreeVectorClass(std::string const &name, std::string const &dir = ".", Int_t splitlevel = 0) {
   TFile f((dir + "/" + name + ".root").c_str(), "RECREATE"); // Create file
   TTree tree(name.c_str(), "Tree with a vector containing objects"); // Create tree

   // Leaf variables
   std::vector<Particle> vp;
   Particle p;

   // Create branch
   tree.Branch("vp", &vp, 32000, splitlevel);

   // Fill tree
   for (Int_t j = 1; j < 11; ++j) {
      vp.clear();

      for (Int_t k = 0; k < 5; ++k) {
         p.fPosX = 100 * j + 10 + k;
         p.fPosY = 100 * j + 20 + k;
         p.fPosZ = 100 * j + 30 + k;
         vp.push_back(p);
      }

      tree.Fill();
   }

   f.Write(); f.Close(); // Write tree to file
}

void generateTreeClassWithArray(std::string const &name, std::string const &dir = ".") {
   TFile f((dir + "/" + name + ".root").c_str(), "RECREATE"); // Create file
   TTree tree(name.c_str(), "Tree with a class containing an array"); // Create tree

   ClassWithArray *classWithArray = new ClassWithArray(); // One instance to fill the tree

   // Create branch for ClassWithArray
   tree.Branch("ClassWithArray_branch", &classWithArray);

   // Fill tree
   for (Int_t i = 1; i < 11; ++i) {
      for(Int_t j = 0; j < 10; ++j)
         classWithArray->arr[j] = 100 * i + j;

      tree.Fill();
   }

   f.Write(); f.Close(); // Write tree to file
}

void generateTreeClassWithVector(std::string const &name, std::string const &dir = ".") {
   TFile f((dir + "/" + name + ".root").c_str(), "RECREATE"); // Create file
   TTree tree(name.c_str(), "Tree with a class containing a vector"); // Create tree

   ClassWithVector *classWithVector = new ClassWithVector(); // One instance to fill the tree

   // Create branch for ClassWithVector
   tree.Branch("ClassWithVector_branch", &classWithVector);

   // Fill tree
   for (Int_t i = 1; i < 11; ++i) {
      classWithVector->vec.clear();
      classWithVector->vecBool.clear();
      for(Int_t j = 0; j < 5; ++j) {
         classWithVector->vec.push_back(100 * i + j);
         classWithVector->vecBool.push_back(j % 2);
      }

      tree.Fill();
   }

   f.Write(); f.Close(); // Write tree to file
}

void generateTreeClassWithClones(std::string const &name, std::string const &dir = ".") {
   TFile f((dir + "/" + name + ".root").c_str(), "RECREATE"); // Create file
   TTree tree(name.c_str(), "Tree with a class containing a TClonesArray"); // Create tree

   ClassWithClones *classWithClones = new ClassWithClones(); // One instance to fill the tree
   classWithClones->arr.SetOwner(kTRUE);

   // Create branch for ClassWithClones
   tree.Branch("ClassWithClones_branch", &classWithClones, 32000, 99);

   // Fill tree
   for (Int_t i = 1; i < 11; ++i) {
      classWithClones->arr.Clear();
      for(Int_t j = 0; j < 5; ++j) {
         new (classWithClones->arr[j]) Particle();
         Particle *p = (Particle*)classWithClones->arr[j];
         p->fPosX = 100 * i + 10 + j;
         p->fPosY = 100 * i + 20 + j;
         p->fPosZ = 100 * i + 30 + j;
      }
      tree.Fill();
   }

   f.Write(); f.Close(); // Write tree to file
}

// Generate trees
void generateAll() {
   std::string const dir = "./trees";
   generateTreeVectorClass("TreeVectorClass0", dir, 0);
   generateTreeVectorClass("TreeVectorClass2", dir, 2);
   generateTreeClassWithArray("TreeClassWithArray", dir);
   generateTreeClassWithVector("TreeClassWithVector", dir);
   generateTreeClassWithClones("TreeClassWithClones", dir);
}

// Run all tests (assuming that the trees are already generated by
// 'generateAll()' and the selectors are implemented in files
// 'selector.C_filled')
void testCollectionClasses() {
   const char *dirSaved = gSystem->pwd(); // Save working directory

   // Loop through test trees
   std::vector<std::string> trees = {"TreeVectorClass0",
                                     "TreeVectorClass2",
                                     //"TreeClassWithArray", // Known failure
                                     "TreeClassWithVector",
                                     "TreeClassWithClones"
                                     };
   for (std::string treeName : trees)
   {
      fprintf(stderr, "Testing tree %s\n", treeName.c_str());

      TFile f(("./trees/" + treeName + ".root").c_str()); // Load file
      TTree *t = (TTree*)f.Get(treeName.c_str());         // Load tree
      gSystem->cd("./generated_selectors");               // Go to gen. folder
      t->MakeSelector();                                  // Generate selector
      gSystem->cd("..");                                  // Go back
      t->Process(("./test_selectors/" + treeName + ".C").c_str()); // Run (pre-filled) selector
   }
   gSystem->cd(dirSaved); // Restore working directory
}
